### ISSUE TITLE
Exception on some cases

### ISSUE THREAD

**Issue by feyst** [sin9270/simple-base-converter#15]
Hi,

For some cases it triggers an exception that I don't understand. Consider the following:
```
const {convertBase} = require("simple-base-converter");

const num = '9999999999';
const numBase = '0123456789';
const base = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_';

// value: '9k2-f_'
const base64 = convertBase(num, numBase, base);

// Exception: 'First augument must consist of second augument.'
const convertedBack = convertBase(base64, base, numBase);

console.log(convertedBack)
```
The last convert back to normal throws an exception when running in node 16.13.

Do you have any idea why this happens?

**Comment by sin9270** [comment]
@feyst 
Sorry for the late reply and thanks for the bug report.
@rxdvd found the cause of the problem and he solved it.
Thanks you both!
